Add suite-level filter and runtime mocha args
TestArmada/magellan-mocha-plugin pull request #18
Opened 2017-04-18 15:14 UTC by hoverduck

I realize it's an anti-pattern with mocha, but my tests are constructed with dependencies in between `it()`blocks in a suite.  This PR adds a capability to the Magellan mocha plugin to make specifically-tagged _suites_ as the main unit of testing, rather than the individual tests themselves.

Usage: `magellan --suiteTag=parallel` will run every `describe()` block that's tagged with `@parallel`

I've also added a feature to add runtime arguments to mocha (as opposed to limiting them to the `mocha.opts` file).  The use case for this is that I have arguments (a specific reporter) that I want included every time Magellan runs, but not when I'm running mocha manually.

Usage: `magellan --mocha_args="-R reporter"`

I'd love some feedback on my approach, and whether it's something that can be incorporated when the mocha plugin supports Magellan 10.0 or if I'll need a different approach.

Thanks!

2017-04-20 23:30 UTC, archlichking commented
@hoverduck your test failed in linting.

2017-06-29 00:12 UTC, archlichking commented
@hoverduck this time your test failed in unit test.  The easiest way to mimic what travis does for this PR verify is `npm run coverage` in your local.

2017-06-29 13:45 UTC, hoverduck commented
@archlichking Yep, I'm working on it.  Sorry for the long delay :/

2017-06-29 14:41 UTC, hoverduck commented
Tests all running clean now!

2017-10-18 19:04 UTC, hoverduck commented
@archlichking Any chance I could get this merged?  I've got some other changes in mind and I'd like to make sure I'm working off a clean baseline :smile:

2017-10-18 23:43 UTC, archlichking requested changes

2017-10-18 23:43 UTC, archlichking commented on lib/help.js
> +  mochaArgs: {
please follow testarmada's delimited command line args convention. for example, `mochaArgs` should be `mocha_args`. the entries in `help.js` will be part of magellan's `--help` output to the console.

2017-10-18 23:43 UTC, archlichking commented on lib/help.js
> +  suiteTag: {
same here, please follow testarmada's delimited command line args convention.

2017-10-18 23:43 UTC, archlichking commented on lib/help.js
> +  suiteTag: {
maybe `suite_tags` is better?

2017-10-18 23:43 UTC, archlichking commented on lib/suite_capture.js
> +function getSuites(suite, wantedTag) {
does this function support multiple tags? does it support locating suite with tag @c as multi level nested test suite like 
```
describe("a @a", ()=>{
  describe("b @b", ()=>{
    describe("c @c", ()=>{
      it("test", ()=>{});
    });
  });
});
```

2019-08-13 15:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/TestArmada/magellan-mocha-plugin?pullRequest=18) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/TestArmada/magellan-mocha-plugin?pullRequest=18) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/TestArmada/magellan-mocha-plugin?pullRequest=18) it.</sub>

2019-08-13 18:42 UTC, closed without merging